### PR TITLE
404+unauthorized addons

### PR DESCRIPTION
**Pull request by pisanty**
Created the file errorPages to the components and in it two pages for "unauthorized" and "missing" pages.
App.tsx was also updated accordingly.

### CODE REVIEW

**Comment by pisanty** [comment]
It fails and I just can't make it work.. I will check it again tomorrow morning before the meeting.. If you have any suggestions, please, help.

**Comment by Eelii** [comment]
> It fails and I just can't make it work.. I will check it again tomorrow morning before the meeting.. If you have any suggestions, please, help.

There was a typo in style props, which created some weird errors. Styles should have been passed as objects, and CSS **text-align** should be a key named **textAlign**, which is a bit confusing. 
Also, Navigation was imported from react-router-dom instead useNavigation.  
Seems to be working otherwise 😊👍

**Review by Eelii — APPROVED** [review]

**Comment by ImWuX** [comment]
Looks good, I would recommend changing the buttons redirect path to / as it's more future proof

**Comment by pisanty** [comment]
@ImWuX @Eelii 

Merge?

**Comment by ImWuX** [comment]
> @ImWuX @Eelii
> 
> Merge?

There is a merge conflict

**Pull request merged**
