### PR TITLE
Add emails

### PR DESCRIPTION
**Pull request by mpsib**
- add email when registering
- use email to login
- see email in admin user page

this is paired with addEmails branch/PR from backend https://github.com/LibraryProjectGroup/library-project-backend/pull/82

for issue https://github.com/LibraryProjectGroup/library-project/issues/80

### CODE REVIEW

**Comment by Eelii** [comment]
🤖❔

**Comment by mpsib** [comment]
some things about robot tests regarding this PR:

- I changed the error messages for login failures since specifying which parameter is wrong is a security risk
- creating account requires an email which isn't implemented in robot yet

**Review by Eelii — APPROVED** [review]
Great 👍

**Comment by AnjaMis** [comment]
Should we ask devops team to take a look at this?

**Comment by Eelii** [comment]
> Should we ask devops team to take a look at this?

Maybe. Still haven't got a totally clear picture on how the testing is currently implemented, but backend test are complaining about 502 (bad gateway), so there might be something up with https://libraryproject.ddns.net. Could also be that the test haven't kept up with the features (ATDD still a work in progress 😅).

**Comment by el1sa** [comment]
> > Should we ask devops team to take a look at this?
> 
> Maybe. Still haven't got a totally clear picture on how the testing is currently implemented, but backend test are complaining about 502 (bad gateway), so there might be something up with https://libraryproject.ddns.net. Could also be that the test haven't kept up with the features (ATDD still a work in progress 😅).

The 502 code on the backend has usually come when the docker has crashed, please check the conversation on discord attention-needed - channel.

**Comment by el1sa** [comment]
> > Should we ask devops team to take a look at this?
> 
> Maybe. Still haven't got a totally clear picture on how the testing is currently implemented, but backend test are complaining about 502 (bad gateway), so there might be something up with https://libraryproject.ddns.net. Could also be that the test haven't kept up with the features (ATDD still a work in progress 😅).

Plus on the frontend side, if you make changes to UI, it'll most likely affect the test cases too, keep that one as a good "nyrkkisääntö". Now it seems that login is failing since the correct element cannot be found. Plus now there has been some changes in the backend that our team has not been aware of and that is why the cases that require login are failing.

**Pull request merged**
